apiVersion: apps/v1
kind: Deployment
metadata:
  name: travel-ui
  namespace: hackathon2023-prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: travel-ui
  template:
    metadata:
      labels:
        app: travel-ui
    spec:
      containers:
      - name: travel-ui
        image: image-registry.openshift-image-registry.svc:5000/hackathon2023-prometheus/trav-reco-ui
        ports:
        - containerPort: 8000
