apiVersion: v1
kind: Service
metadata:
  name: nodejs-svc
  namespace: hackathon2023-prometheus
spec:
  ports:
    - name: nodejs-svc
      port: 8081
      targetPort: 8081
  selector:
    app: nodejs-basic
  type: LoadBalancer
