apiVersion: v1
kind: Service
metadata:
  name: travel-ui
  namespace: hackathon2023-prometheus
spec:
  ports:
    - name: port-svc
      port: 8000
      targetPort: 8080
  selector:
    app: travel-ui
  type: LoadBalancer
